candidates/urls.py
from django.urls import path

from . import views

app_name = 'candidates'
urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add, name='add'),
    path('<int:pk>/', views.show, name='show'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/vote/', views.vote, name='vote'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView

from . import views


urlpatterns = [
    path('hello/', views.hello),
    path('bmi/', views.bmi),
    path('candidates/', include('candidates.urls')),
    path('admin/', admin.site.urls),

    path('', views.root, name='root'),
    path('login/', LoginView.as_view(
        redirect_authenticated_user=True,
    ), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

candidates/models.py
import os
import time

from django.db import models
from django.contrib.auth.models import User


def candidate_image_path(instance, filename):
    ext = os.path.splitext(filename)[-1]
    now = str(time.time()).replace('.', '')
    f_name = '{}{}'.format(now, ext)
    return os.path.join('candidates', f_name)


class Candidate(models.Model):
    name = models.CharField('姓名', max_length=50)
    politics = models.TextField('政見')
    age = models.PositiveIntegerField('年齡')
    image = models.ImageField('圖片', null=True, blank=True, upload_to=candidate_image_path)

    def __str__(self):
        return self.name


class Vote(models.Model):
    user = models.OneToOneField(User, models.CASCADE)
    candidate = models.ForeignKey(Candidate, models.CASCADE)

candidates/forms.py
from django import forms

from .models import Candidate, Vote


class CandidateForm(forms.ModelForm):
    class Meta:
        model = Candidate
        fields = '__all__'


class VoteForm(forms.ModelForm):
    class Meta:
        model = Vote
        fields = '__all__'

core/forms.py
from django import forms


class BmiForm(forms.Form):
    h = forms.FloatField(min_value=1, label='身高')
    w = forms.FloatField(min_value=1, label='體重')


class DeleteConfirmForm(forms.Form):
    check = forms.BooleanField(label='你確定要刪除嗎？')

candidates/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from core.forms import DeleteConfirmForm

from .models import Candidate
from .forms import CandidateForm, VoteForm


@login_required
def index(request):
    candidates = Candidate.objects.all()
    return render(request, 'candidates/index.html', {
        'candidates': candidates,
    })


@login_required
def add(request):
    form = CandidateForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        candidate = form.save()
        messages.success(request, '新增成功')
        return redirect('candidates:show', pk=candidate.pk)

    return render(request, 'candidates/add.html', {
        'form': form,
    })


@login_required
def edit(request, pk):
    candidate = get_object_or_404(Candidate, pk=pk)
    form = CandidateForm(request.POST or None, request.FILES or None, instance=candidate)
    if form.is_valid():
        candidate = form.save()
        messages.success(request, '編輯成功')
        return redirect('candidates:show', pk=candidate.pk)

    return render(request, 'candidates/edit.html', {
        'form': form,
    })


@login_required
def delete(request, pk):
    candidate = get_object_or_404(Candidate, pk=pk)
    form = DeleteConfirmForm(request.POST or None)
    if form.is_valid():
        candidate.delete()
        messages.success(request, '刪除成功')
        return redirect('candidates:index')

    return render(request, 'candidates/delete.html', {
        'form': form,
    })


@login_required
def show(request, pk):
    candidate = get_object_or_404(Candidate, pk=pk)
    return render(request, 'candidates/show.html', {
        'candidate': candidate,
    })


@login_required
def vote(request, pk):
    candidate = get_object_or_404(Candidate, pk=pk)
    form = VoteForm({'candidate': candidate.pk, 'user': request.user.pk})

    if form.is_valid():
        messages.success(request, 'Vote success')
        form.save()
    else:
        messages.warning(request, form.errors)

    return redirect('candidates:index')

core/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login

from .forms import BmiForm


def hello(request):
    return HttpResponse('Hello World')


# http://127.0.0.1:8000/bmi/?h=100&w=50
def bmi(request):
    form = BmiForm(request.POST or None)
    if form.is_valid():
        h = form.cleaned_data['h']
        w = form.cleaned_data['w']
        bmi = w / ((h / 100) ** 2)
        return render(request, 'bmi.html', {'bmi': bmi})

    return render(request, 'bmi-input.html', {'form': form})


def root(request):
    return render(request, 'root.html')


def register(request):
    form = UserCreationForm(request.POST or None)
    if form.is_valid():
        user = form.save()
        login(request, user)
        return redirect('root')

    return render(request, 'register.html', {'form': form})

templates/bmi-input.html
{# Load the tag library #}
{% load bootstrap4 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

<div class="row m-3">
  <div class="col">
    <form action="" method="POST">
      {% csrf_token %}

      {% bootstrap_form form %}

      {% buttons %}
      <button type="submit" class="btn btn-primary">
        Submit
      </button>
      {% endbuttons %}
    </form>
  </div>
</div>

templates/bmi.html
<h1>BMI: {{ bmi }}</h1>

templates/candidates/add.html
{% extends 'layout.html' %}

{% block main %}
<div class="row">
  <div class="col col-md-8 offset-md-2 col-lg-6 offset-lg-3">
    <h1>新增候選人</h1>
    <hr>
    {% include 'shared/form.html' %}
    <img id="preview">
  </div>
</div>

<script>
  function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();

      reader.onload = function (e) {
        $('#preview').attr('src', e.target.result);
      }

      reader.readAsDataURL(input.files[0]);
    }
  }

  $('#id_image').change(function () {
    readURL(this);
  })
</script>
{% endblock %}

templates/candidates/delete.html
{% extends 'layout.html' %}

{% block main %}
  <div class="row">
    <div class="col col-md-8 offset-md-2 col-lg-6 offset-lg-3">
      <h1>刪除候選人</h1>
      <hr>
      {% include 'shared/form.html' %}
    </div>
  </div>
{% endblock %}

templates/candidates/edit.html
{% extends 'layout.html' %}

{% block main %}
  <div class="row">
    <div class="col col-md-8 offset-md-2 col-lg-6 offset-lg-3">
      <h1>編輯候選人</h1>
      <hr>
      {% include 'shared/form.html' %}

      <img id="preview" {% if form.instance.image %}src="{{ form.instance.image.url }}"{% endif %}>

    </div>
  </div>

  <script>
    function readURL(input) {
      if (input.files && input.files[0]) {
        var reader = new FileReader();

        reader.onload = function (e) {
          $('#preview').attr('src', e.target.result);
        }

        reader.readAsDataURL(input.files[0]);
      }
    }

    $('#id_image').change(function () {
      readURL(this);
    })
  </script>
{% endblock %}

templates/candidates/index.html
{% extends 'layout.html' %}

{% block main %}
<div class="row">
  <div class="col">
    <a class="btn btn-outline-info float-right" href="{% url 'candidates:add' %}">新增</a>
    <h1>候選人列表</h1>
    <hr>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">名字</th>
          <th scope="col">年齡</th>
          <th scope="col">得票數</th>
          <th scope="col">操作</th>
        </tr>
      </thead>
      <tbody>
        {% for candidate in candidates %}
        <tr>
          <th scope="row">{{ candidate.pk }}</th>
          <td>
            <a href="{% url 'candidates:show' candidate.pk %}">{{ candidate.name }}</a>
          </td>
          <td>{{ candidate.age }}</td>
          <td>{{ candidate.vote_set.count }}</td>
          <td>
            <a class="btn btn-sm btn-warning" href="{% url 'candidates:edit' candidate.pk %}">編輯</a>
            <a class="btn btn-sm btn-danger" href="{% url 'candidates:delete' candidate.pk %}">刪除</a>
            <a class="btn btn-sm btn-success" href="{% url 'candidates:vote' candidate.pk %}">投票給他</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

templates/candidates/show.html
{% extends 'layout.html' %}

{% block main %}
<div class="row">
  <div class="col">
    <h1>#{{ candidate.pk }} {{ candidate.name}}</h1>
    <hr>
    <p>名字：{{ candidate.name }}</p>
    <p>年紀：{{ candidate.age }} 歲</p>
    <p>證件：{{ candidate.politics | linebreaks }}</p>

    {% if candidate.image %}
      <hr>
      <img src="{{ candidate.image.url }}" alt="{{ candidate.name }}">
    {% endif %}
  </div>
</div>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Django Playground</title>

  {# Load the tag library #}
  {% load bootstrap4 %}

  {# Load CSS and JavaScript #}
  {% bootstrap_css %}
  {% bootstrap_javascript jquery='full' %}
</head>

<body>
  <div class="row bg-dark p-3">
    {% if request.user.is_authenticated %}
      <div class="col text-center">
        <a class="btn btn-info btn-sm" href="{% url 'logout' %}">Logout</a>
      </div>
    {% else %}
      <div class="col text-center">
        <a class="btn btn-info btn-sm" href="{% url 'login' %}">Login</a>
      </div>
      <div class="col text-center">
        <a class="btn btn-info btn-sm" href="{% url 'register' %}">Register</a>
      </div>
    {% endif %}

    <div class="col text-center">
      <a class="btn btn-info btn-sm" href="{% url 'candidates:index' %}">Candidate List</a>
    </div>
  </div>

  <div class="container my-3">
    {% bootstrap_messages %}
    {% block main %}{% endblock %}
  </div>
</body>

</html>

templates/register.html
{% extends 'layout.html' %}

{% block main %}
<div class="row">
  <div class="col col-md-8 offset-md-2 col-lg-6 offset-lg-3">
    <h1>Register</h1>
    <hr>
    {% include 'shared/form.html' %}
  </div>
</div>
{% endblock %}

templates/root.html
{% extends 'layout.html' %}

{% block main %}
<div class="row">
  <div class="col">
    <h1>Hello World</h1>
    <hr>
    <p>
      {% if request.user.is_authenticated %}
        Welcome, {{ request.user.username }}
      {% else %}
        Click <a href="{% url 'login' %}">here</a> to login
      {% endif %}
    </p>
  </div>
</div>
{% endblock %}

templates/shared/form.html
{% load bootstrap4 %}

<form action="" method="POST" enctype="multipart/form-data">
  {% csrf_token %}

  {% bootstrap_form form %}

  {% buttons %}
  <button type="submit" class="btn btn-primary">
    送出
  </button>
  {% endbuttons %}
</form>